# Generated by Django 5.2.14 on 2026-05-08 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_video_visibility_repost_savedvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="post_type",
            field=models.CharField(
                choices=[("video", "Video"), ("photo", "Photo Carousel")],
                default="video",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.CreateModel(
            name="PhotoSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="slides/")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
