# Generated by Django 5.2.14 on 2026-05-09 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_video_post_type_alter_video_video_file_photoslide"),
    ]

    operations = [
        migrations.AddField(
            model_name="videocomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="videos.videocomment",
            ),
        ),
    ]
