# Generated by Django 5.2.14 on 2026-05-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="cover",
        ),
        migrations.AddField(
            model_name="user",
            name="is_live",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="live_title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
